### ISSUE TITLE
Confusion about loss

### ISSUE THREAD

**Issue by pearl-rabbit** [ckczzj/PDAE#5]
Hello, the symbol in front of gradient estimator G in formula (7) and Appendix A of the paper is '+', but the text description after formula (7)  and code  use '-'.  I am a bit confused about this, and I hope you can help me answer it.

**Comment by ckczzj** [comment]
In paper, the loss of certain timestep is:
![CodeCogsEqn (1)](https://github.com/ckczzj/PDAE/assets/23724208/f8d495bc-e554-478f-bf40-1b2cdc1baad9),
and you can write it as:
![CodeCogsEqn](https://github.com/ckczzj/PDAE/assets/23724208/76c3576f-6a12-4a94-99e9-42483a89a0cc),
where 
![CodeCogsEqn (1)](https://github.com/ckczzj/PDAE/assets/23724208/d99a8af0-2120-4a7f-b529-57f31de09c2b)
is just the shift_coef defined here:
https://github.com/ckczzj/PDAE/blob/fbba0355634861196aed8b80b9ba4948ed210ab9/model/diffusion/gaussian_diffusion.py#L56

**Comment by pearl-rabbit** [comment]
Thanks for your helpful reply, now I understand.
