### ISSUE TITLE
Is it possible to fine-tune pre-trained diffusion model?

### ISSUE THREAD

**Issue by TakeruShiraishi** [ckczzj/PDAE#8]
The use of pre-trained model is very important because collecting large amounts of data is not easy.
While, in my study, pre-trained models that are all over the place is far from the research areas of focus, so I want to fine tune the domain of generated image.
Is it possible to fine tune the pre-trained model in this repository? Alternatively, is it possible to incorporate a fine-tuned model into PDAE using code in other github repositories?

**Comment by ckczzj** [comment]
Thanks for your attention.

We have included the code for training the regular ddpm for this [issue](https://github.com/ckczzj/PDAE/issues/1). You can load some pre-trained model before training to fine-tune it. For example, you can add the loading code after [this line](https://github.com/ckczzj/PDAE/blob/56c394f8f6df7806fc71484c5f9b7726d709ee92/trainer/train_regular_diffusion.py#L27C133-L27C133) and then run `scripts/dist_train_regular_diffusion.sh` to fine-tune it.

**Comment by TakeruShiraishi** [comment]
Thank you so much!
